### PR TITLE
Reword ECR IAM Role config description

### PR DESCRIPTION
**Pull request by acosta11**
After updating the documentation for the repository configuration in general, there wasn't much left to change specifically for ECR. We mostly wanted to ensure the description was not confusing with its use of "similar" to a value used in TBS instead of saying it can in fact be the same one and pointing back to the TBS documentation.

### CODE REVIEW

**Comment by julian-hj** [comment]
I am not sure that this description is sufficient. The IAM role we configure for use by TAS-Adapter needs to include rights to create new repos (since we now make one per application) and also needs to include some additional service accounts that are allowed to use it.

See https://gitlab.eng.vmware.com/tanzu-application-platform/dap-tas-migration-enablement/tas-adapter-ci/-/blob/main/ci/deploy/eks/eks-role.tf for the list of service accounts & actions we allow in CI. (Note that the list of resources in this role definition is probably overbroad, and could be constrained to just the buckets we need.)

**Comment by emalm** [comment]
Are the IAM roles in https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.4/tap/aws-resources.html adequate for these docs to link to, or does the TAS Adapter installation need different roles for it to work?

**Comment by julian-hj** [comment]
@emalm no they aren't sufficient--we are working on revising this PR today.

**Comment by julian-hj** [comment]
@emalm we're done with our edits to this PR. PTAL.

(As a side note, I am not super happy with the placement for the IAM role configuration, but we weren't sure where else to put it.)

**Pull request merged**
